runtime: python27
api_version: 1
threadsafe: true


handlers:

- url: /
  script: server.main.app
  secure: always

- url: /speak/.*
  script: server.mary.app

- url: /see
  script: server.vision.app

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|svg|ttf))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png|svg|ttf))

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html

# audio files
- url: /(.*\.mp3)
  mime_type: audio/mpeg
  static_files: static/\1
  upload: static/audio/(.*\.mp3)


skip_files:
- ^(.*/)?.*\.pyc
- ^(.*/)?.*\.wav
- ^.git/.*
- ^(.*/)?node_modules/.*
- ^static/src/.*
- ^static/style/.*
- ^package\.json

libraries:
- name: webapp2
  version: latest

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: PATH/TO/CLOUD_VISION_KEY.json